import starCatalog from './stars.yaml'
import constellationCatalog from './constellations.yaml'

export type Star = {
  id: string
  name: string
  constellation: string
  raHours: number
  decDeg: number
  magnitude: number
  color: string
}

export type ConstellationLine = {
  name: string
  segments: string[][]
}

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null

function readStars(value: unknown): Star[] {
  if (!isRecord(value) || !Array.isArray(value.stars)) throw new Error('stars.yaml 格式无效')
  return value.stars.map((item) => {
    if (!isRecord(item)) throw new Error('stars.yaml 含有无效恒星记录')
    const star = {
      id: String(item.id),
      name: String(item.name),
      constellation: String(item.constellation),
      raHours: Number(item.raHours),
      decDeg: Number(item.decDeg),
      magnitude: Number(item.magnitude),
      color: String(item.color),
    }
    if (!star.id || Number.isNaN(star.raHours) || Number.isNaN(star.decDeg) || Number.isNaN(star.magnitude)) {
      throw new Error(`stars.yaml 恒星数据不完整: ${star.id || '?'}`)
    }
    return star
  })
}

function readConstellations(value: unknown): ConstellationLine[] {
  if (!isRecord(value) || !Array.isArray(value.constellations)) throw new Error('constellations.yaml 格式无效')
  return value.constellations.map((item) => {
    if (!isRecord(item) || !Array.isArray(item.segments)) throw new Error('constellations.yaml 含有无效星座记录')
    return {
      name: String(item.name),
      segments: item.segments.map((segment) => {
        if (!Array.isArray(segment)) throw new Error(`constellations.yaml 线段无效: ${item.name}`)
        return segment.map((id) => String(id))
      }),
    }
  })
}

// Development-only fixture. Production catalogues are generated by scripts/catalog
// after the source-level commercial licensing gate has passed.
export const namedStars: Star[] = readStars(starCatalog)

export const stars: Star[] = [...namedStars].sort((a, b) => a.magnitude - b.magnitude)

export const starById = new Map(stars.map((star) => [star.id, star]))

export function countStarsThroughMagnitude(limit: number) {
  let low = 0
  let high = stars.length
  while (low < high) {
    const mid = (low + high) >> 1
    if (stars[mid].magnitude <= limit) low = mid + 1
    else high = mid
  }
  return low
}

export const constellationLines: ConstellationLine[] = readConstellations(constellationCatalog)

export const cities = [
  { name: '上海', latitude: 31.2304, longitude: 121.4737, timeZone: 'Asia/Shanghai' },
  { name: '北京', latitude: 39.9042, longitude: 116.4074, timeZone: 'Asia/Shanghai' },
  { name: '伦敦', latitude: 51.5072, longitude: -0.1276, timeZone: 'Europe/London' },
  { name: '纽约', latitude: 40.7128, longitude: -74.006, timeZone: 'America/New_York' },
  { name: '悉尼', latitude: -33.8688, longitude: 151.2093, timeZone: 'Australia/Sydney' },
]

export const defaultCityIndex = Math.max(0, cities.findIndex((city) => city.name === '上海'))
